### ISSUE TITLE
Ошибка установки mysql-server на centos 6.6

### ISSUE THREAD

**Issue by DKLIMASHIN** [gongled/ansible-cscart-deployer#1]
Mysql устанавливается с неправильными линками на сокет.
Правильный конфиг прикладываю:
[client]
port            = 3306
socket          = /var/lib/mysql/mysql.sock

[mysqld_safe]
socket          = /var/lib/mysql/mysql.sock
nice            = 0

[mysqld]
user            = mysql
bind-address    = 0.0.0.0
pid             = /var/run/mysql/mysql.pid
socket          = /var/lib/mysql/mysql.sock
port            = 3306
basedir         = /usr
datadir         = /var/lib/mysql
tmpdir          = /tmp

skip-name-resolve
skip-external-locking
low-priority-updates
log-queries-not-using-indexes

interactive_timeout   = 28800
wait_timeout          = 28800
connect_timeout       = 10
net_read_timeout      = 30
net_write_timeout     = 30

key_buffer            = 32M
max_allowed_packet    = 128M
myisam-recover        = BACKUP
query_cache_type      = 1
query_cache_limit     = 1M
query_cache_size      = 64M

max_connections       = 32
sort_buffer_size      = 4M
read_buffer_size      = 128K
read_rnd_buffer_size  = 1M
join_buffer_size      = 4M
thread_stack          = 192K
thread_cache_size     = 8

general_log_file      = /var/log/mysql/general.log
general_log           = 0
slow_query_log        = /var/log/mysql/slow.log
long_query_time       = 5

[mysqldump]
quick
quote-names
max_allowed_packet    = 128M

# !includedir /etc/mysql/conf.d/

**Comment by gongled** [comment]
Подтверждаю, баг. В процессе исправления.

**Comment by gongled** [comment]
Ошибка исправлена.
